apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
    <head>
      <title>My Custom Nginx Page</title>
    </head>
    <body>
      <h1>MLOPS course!</h1>
    </body>
    </html>
